name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
env:
  GO111MODULE: on
jobs:
  golangci:
    name: lint
    runs-on: [self-hosted, linux, x64, digital-discovery-runner-1]
    steps:
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: git config --global url."https://${USER_NAME}:${TOKEN}@github.com".insteadOf "https://github.com"
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32.2
          args: --timeout=5m

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
